### ISSUE TITLE
unable to evaluate symlinks in Dockerfile path

### ISSUE THREAD

**Issue by dalton-cole** [Azure/docker-login#11]
I have a Dockerfile in the root of my repo but I am still getting
`unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/runner/work/REPONAME/REPONAME/Dockerfile: no such file or directory
##[error]Process completed with exit code 1.` when building.

**Comment by thesattiraju** [comment]
Could you share a snip of your workflow, like how you're building it? And the preceding steps

**Comment by preciz** [comment]
I have the same error.

```
name: BUILD_AND_PUSH_DOCKER

on:
  push:
    branches:
      - preciz/phx

jobs:
  build_and_push_docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: *****.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build --build-arg DATABASE_USER="${{ secrets.DATABASE_USER }}" \
                       --build-arg DATABASE_PASS="${{ secrets.DATABASE_PASS }}" \
                       --build-arg DATABASE_HOST="${{ secrets.DATABASE_HOST }}" \
                       --build-arg DATABASE="${{ secrets.DATABASE }}" \
                       --build-arg SECRET_KEY_BASE="${{ secrets.SECRET_KEY_BASE }}" . -t *****.azurecr.io/docs-elixir:v1
          docker push ******.azurecr.io/docs-elixir:v1

```
