### ISSUE TITLE
Docker Login action breaks other GH Actions that are Docker-related

### ISSUE THREAD

**Issue by ItalyPaleAle** [Azure/docker-login#12]
I spent a while debugging my pipeline and turns out it was because of this action.

I need to use the "buildx" extension for Docker, and it's inside this action: https://github.com/crazy-max/ghaction-docker-buildx

When using the azure/docker-login action to authenticate, buildx didn't work. Replacing the action with a script fixed it.

Broken setup:

```yaml
# Setup Docker buildx
- name: Set up Docker buildx
  id: buildx
  uses: crazy-max/ghaction-docker-buildx@v1
  with:
    version: latest

# Login to Docker Hub
- name: Login to Docker Hub
  uses: azure/docker-login@v1
  with:
    username: ${{env.DOCKER_USERNAME}}
    password: ${{ secrets.DOCKER_PASSWORD }}
```

Working:

```yaml
# Setup Docker buildx
# https://github.com/crazy-max/ghaction-docker-buildx
- name: Set up Docker buildx
  uses: crazy-max/ghaction-docker-buildx@v1
  with:
    version: latest
# Login to Docker Hub
- name: Login to Docker Hub
  env:
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  run: |
    echo "${DOCKER_PASSWORD}" | docker login --username "${{env.DOCKER_USERNAME}}" --password-stdin
```

In both cases, the next instruction is a script that runs `docker buildx build`.
