### ISSUE TITLE
Managed identity authentication support

### ISSUE THREAD

**Issue by t3mi** [Azure/docker-login#25]
Please add support for authentication using managed identity.  We're utilizing a farm of different computes with self-hosted github actions runners and managed identities attached for ease of management so eliminating service principal authentication would be very beneficial option.

**Comment by azooinmyluggage** [comment]
@N-Usha Are we planning to add MSI support? We should update the issue with what is our opinion and plan.

**Comment by ajinkya599** [comment]
@pulkitaggarwl @azooinmyluggage - What's the plan here?

**Comment by Erriez** [comment]
I also need Docker login to self-hosted registry:

```
- name: Login to self-hosted registry
        uses: docker/login-action@v1 
        with:
          login-server: registry.fritz.box
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
```

```
[CI/Build image] ⭐  Run Login to self-hosted registry
INFO[0007]   ☁  git clone 'https://github.com/docker/login-action' # ref=v1 
[CI/Build image]   🐳  docker cp src=/home/a/.cache/act/docker-login-action@v1/ dst=/var/run/act/actions/docker-login-action@v1/
[CI/Build image]   🐳  docker exec cmd=[mkdir -p /var/run/act/actions/docker-login-action@v1/] user=
[CI/Build image]   🐳  docker exec cmd=[node /var/run/act/actions/docker-login-action@v1/dist/index.js] user=
[CI/Build image]   ❓  ::save-state name=isPost::true
[CI/Build image]   ❓  ::save-state name=registry::
[CI/Build image]   ❓  ::save-state name=logout::true
| Logging into Docker Hub...
[CI/Build image]   ❗  ::error::Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

It tries to login to Docker Hub https://registry-1.docker.io/v2/ instead of the provided `login-server`.

Cannot use `docker/login-action@v1`.
