### ISSUE TITLE
It doesn't work because the environment variable won't be passed to the next step

### ISSUE THREAD

**Issue by 0o100** [Azure/docker-login#4]
Here's the config:

```yaml
    - name: Docker Hub Login
      uses: Azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.dockerhub_registry_username }}
        password: ${{ secrets.dockerhub_registry_password }}

    - name: Publish image to Docker Hub
      shell: bash
      run: |
          make push
```

Makefile:
https://github.com/0o100/docker-eureka/blob/master/Makefile

Failure logs:
https://github.com/0o100/docker-eureka/commit/4925128529204566e61546c87a2d3ea472685107/checks?check_suite_id=324214506

```log
2c6ac8e5063e: Waiting
cc967c529ced: Waiting
denied: requested access to the resource is denied
Makefile:38: recipe for target 'push' failed
make: *** [push] Error 1
##[error]Process completed with exit code 2.
```

**Comment by addnab** [comment]
I too was just having this issue. I had my password wrong. It's working now. Check your credentials.

**Comment by 0o100** [comment]
@addnab My credentials were correct. I was just wondering why I need this action, after I successfully logged in with the following single line:

```yaml
docker login docker.io -u ${{ secrets.dockerhub_registry_username }} -p ${{ secrets.dockerhub_registry_password }}
```

**Comment by stefan2904** [comment]
This works. 

("the environment variable won't be passed to the next step" is not relevant since the docker config is used.)

```yml
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
            
    - name: Docker Build & Push
      run: |
        export DOCKER_TAG=docker.pkg.github.com/$GITHUB_REPOSITORY/github-deployment-test:${GITHUB_REF#refs/heads/}
        docker build . -t $DOCKER_TAG 
        docker push $DOCKER_TAG
```

**Comment by ds-ms** [comment]
You could use `${{ env.GITHUB_ACTOR }}` instead. This would do the parsing of the environment variable before it reaches the login logic in the action

**Comment by stefan2904** [comment]
@ds-ms unfortuantely this does _not_ work:

```yml
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ env.GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}
```
