### ISSUE TITLE
Invalid clientid or client secret

### ISSUE THREAD

**Issue by lsmith77** [Azure/docker-login#46]
I suddenly get errors when pushing new docker containers to azure container registry with:
```
unauthorized: Invalid clientid or client secret.
Error: Process completed with exit code 1.
```

It was working fine for exactly a year but started breaking today, so I guess something expired.

My Github Action can be seen below. It fails on the `build nlp api` step but it seems to pass the login step:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/300279/202555104-2ee53c65-425d-448d-b151-4a41937103ff.png">

What since it passes the login step, I don't get what has expired to cause the issue?

```
on: [push]
name: Build a Docker image and Push it to ACR
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Update requirements.txt for Docker image
        run: |
          pipenv requirements > requirements.txt

      # build nlp api
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:${{ github.sha }}
          # release version
          ref=${{ github.ref_name }}
          tag=${ref////-}
          echo $tag
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:$tag
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nlpapi:$tag
```
