### ISSUE TITLE
Add support to authenticate using "Azure federated credentials"

### ISSUE THREAD

**Issue by hashem-alrifai** [Azure/docker-login#56]
**What:** 
Add support to authenticate using Azure Federation Credentials via OIDC, as in [this Microsoft doc](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux)

**Why:**
We are trying to not store secrets (client secret) in Github repo, but this step requires the secret.

**Comment by maxheld83** [comment]
Agreed it'd be nice if the docker-login action supported OIDC somehow out of the box.

In the meantime, I just used the az CLI to leverage my OIDC setup:


```yaml
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_GITHUB_AUTH }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to ACR via OIDC
        run: az acr login --name <registry-name>
```

**Comment by itpropro** [comment]
Any progress on this? OIDC is the security best practice to authenticate against Azure and it's still not supported. 
It would already be enough if this action would support token based authentication (https://learn.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli#az-acr-login-with---expose-token) against the ACR, as the Azure CLI action already supports OIDC:

```yaml
      - name: Get ACR credentials
        id: get-acr-credentials
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            echo "ACR_ACCESS_TOKEN=$(az acr login --name <ACRNAME> --expose-token --output tsv --query accessToken)" >> "$GITHUB_OUTPUT"
            echo "ACR_LOGIN_SERVER=$(az acr login --name <ACRNAME> --expose-token --output tsv --query loginServer)" >> "$GITHUB_OUTPUT"

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.get-acr-credentials.outputs.ACR_LOGIN_SERVER }}
          username: 00000000-0000-0000-0000-000000000000
          password: ${{ steps.get-acr-credentials.outputs.ACR_ACCESS_TOKEN }}
```

The current workaround without using the `login-action` is this:

```yaml
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: az acr login --name $ACR_NAME
        env:
          ACR_NAME: ${{ vars.ACR_NAME }}
```
