### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by migg24** [Azure/docker-login#66]
Last real update is from 2022, a nice PR updating to node 20 is open and needed, but ignored. As well as other open issues.

Is there still somebody here maintaining the action?

**Comment by soderlind** [comment]
I replaced this action with `docker/login-action`

```yaml

        name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: <registry-name>.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
 ```
 
  docker/login-action@v3 [uses Node 20 as default runtime](https://github.com/docker/login-action/releases/tag/v3.0.0).
