### ISSUE TITLE
Cannot Pull Private Images From Docker Hub

### ISSUE THREAD

**Issue by eligundry** [Azure/docker-login#7]
I wanted to be able to pull a previously pushed image to use as a build cache in our Github actions. The following failed:

```yml
- uses: azure/docker-login@v1
  with:
    login-server: index.docker.io
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}

- name: Docker Pull Cache
  run: |
    docker pull private/repo:latest
```

Whereas, logging in with the Docker CLI tool works:

```yml
- name: Docker Login (Redneck Style)
  run: docker login --username='${{ secrets.DOCKER_USERNAME }}' --password='${{ secrets.DOCKER_PASSWORD }}'

- name: Docker Pull Cache
  run: |
    docker pull private/repo:latest
```

I suspect this is because `docker login` initiates an OAuth2 flow with scopes that allow pulling and that this action just base64 encodes an auth header that won't allow pulling for security reasons.
